export type Station = {
  value: string;
  label: string;
};

export const stations: Station[] = [
  { value: "Abbey_Road", label: "Abbey Road" },
  { value: "Abbey_Wood", label: "Abbey Wood" },
  { value: "Acton_Central", label: "Acton Central" },
  { value: "Acton_Main_Line", label: "Acton Main Line" },
  { value: "Acton_Town", label: "Acton Town" },
  { value: "Aldgate", label: "Aldgate" },
  { value: "Aldgate_East", label: "Aldgate East" },
  { value: "All_Saints", label: "All Saints" },
  { value: "Alperton", label: "Alperton" },
  { value: "Amersham", label: "Amersham" },
  { value: "Anerley", label: "Anerley" },
  { value: "Angel", label: "Angel" },
  { value: "Archway", label: "Archway" },
  { value: "Arnos_Grove", label: "Arnos Grove" },
  { value: "Arsenal", label: "Arsenal" },
  { value: "Baker_Street", label: "Baker Street" },
  { value: "Balham", label: "Balham" },
  { value: "Bank_Monument_hub", label: "Bank Monument Hub" },
  { value: "Barbican", label: "Barbican" },
  { value: "Barking", label: "Barking" },
  { value: "Barking_Riverside", label: "Barking Riverside" },
  { value: "Barkingside", label: "Barkingside" },
  { value: "Barons_Court_district", label: "Barons Court District" },
  { value: "Barons_Court_piccadilly", label: "Barons Court Piccadilly" },
  { value: "Battersea_Park", label: "Battersea Park" },
  { value: "Battersea_Power_Station", label: "Battersea Power Station" },
  { value: "Bayswater_circle", label: "Bayswater Circle" },
  { value: "Bayswater_district", label: "Bayswater District" },
  { value: "Beckton", label: "Beckton" },
  { value: "Beckton_Park", label: "Beckton Park" },
  { value: "Becontree", label: "Becontree" },
  { value: "Belsize_Park", label: "Belsize Park" },
  { value: "Bermondsey", label: "Bermondsey" },
  { value: "Bethnal_Green", label: "Bethnal Green" },
  { value: "Bethnal_Green_central", label: "Bethnal Green Central" },
  { value: "Blackfriars", label: "Blackfriars" },
  { value: "Blackhorse_Road", label: "Blackhorse Road" },
  { value: "Blackwall", label: "Blackwall" },
  { value: "Bond_Street", label: "Bond Street" },
  { value: "Borough", label: "Borough" },
  { value: "Boston_Manor", label: "Boston Manor" },
  { value: "Bounds_Green", label: "Bounds Green" },
  { value: "Bow_Church", label: "Bow Church" },
  { value: "Bow_Road", label: "Bow Road" },
  { value: "Brent_Cross", label: "Brent Cross" },
  { value: "Brentwood", label: "Brentwood" },
  { value: "Brixton", label: "Brixton" },
  { value: "Brockley", label: "Brockley" },
  { value: "Bromley-by-Bow_district", label: "Bromley-By-Bow District" },
  { value: "Bromley-by-Bow_hnc", label: "Bromley-By-Bow Hnc" },
  { value: "Brondesbury", label: "Brondesbury" },
  { value: "Brondesbury_Park", label: "Brondesbury Park" },
  { value: "Bruce_Grove", label: "Bruce Grove" },
  { value: "Buckhurst_Hill", label: "Buckhurst Hill" },
  { value: "Burgess_Park", label: "Burgess Park" },
  { value: "Burnham", label: "Burnham" },
  { value: "Burnt_Oak", label: "Burnt Oak" },
  { value: "Bush_Hill_Park", label: "Bush Hill Park" },
  { value: "Bushey", label: "Bushey" },
  { value: "Caledonian_Road", label: "Caledonian Road" },
  {
    value: "Caledonian_Road_and_Barnsbury",
    label: "Caledonian Road And Barnsbury",
  },
  { value: "Cambridge_Heath", label: "Cambridge Heath" },
  { value: "Camden_Road", label: "Camden Road" },
  { value: "Camden_Town", label: "Camden Town" },
  { value: "Canada_Water", label: "Canada Water" },
  { value: "Canary_Wharf_dlr", label: "Canary Wharf Dlr" },
  { value: "Canary_Wharf_elizabeth", label: "Canary Wharf" },
  { value: "Canary_Wharf_jubilee", label: "Canary Wharf Jubilee" },
  { value: "Canning_Town", label: "Canning Town" },
  { value: "Cannon_Street", label: "Cannon Street" },
  { value: "Canonbury", label: "Canonbury" },
  { value: "Canons_Park", label: "Canons Park" },
  { value: "Carpenders_Park", label: "Carpenders Park" },
  { value: "Castle_Bar_Park", label: "Castle Bar Park" },
  { value: "Castle_Green", label: "Castle Green" },
  { value: "Chadwell_Heath", label: "Chadwell Heath" },
  { value: "Chalfont_and_Latimer", label: "Chalfont And Latimer" },
  { value: "Chalk_Farm", label: "Chalk Farm" },
  { value: "Chancery_Lane", label: "Chancery Lane" },
  { value: "Charing_Cross", label: "Charing Cross" },
  { value: "Chesham", label: "Chesham" },
  { value: "Cheshunt", label: "Cheshunt" },
  { value: "Chigwell", label: "Chigwell" },
  { value: "Chingford", label: "Chingford" },
  { value: "Chiswick_Park", label: "Chiswick Park" },
  { value: "Chorleywood", label: "Chorleywood" },
  { value: "Clapham_Common", label: "Clapham Common" },
  { value: "Clapham_High_Street", label: "Clapham High Street" },
  { value: "Clapham_Junction", label: "Clapham Junction" },
  { value: "Clapham_North", label: "Clapham North" },
  { value: "Clapham_South", label: "Clapham South" },
  { value: "Clapton", label: "Clapton" },
  { value: "Cockfosters", label: "Cockfosters" },
  { value: "Colindale", label: "Colindale" },
  { value: "Colliers_Wood", label: "Colliers Wood" },
  { value: "Covent_Garden", label: "Covent Garden" },
  { value: "Crossharbour", label: "Crossharbour" },
  { value: "Crouch_Hill", label: "Crouch Hill" },
  { value: "Croxley", label: "Croxley" },
  { value: "Crystal_Palace", label: "Crystal Palace" },
  { value: "Custom_House_for_ExCeL", label: "Custom House For ExCeL" },
  {
    value: "Cutty_Sark_for_Maritime_Greenwich",
    label: "Cutty Sark For Maritime Greenwich",
  },
  { value: "Cyprus", label: "Cyprus" },
  { value: "Dagenham_East", label: "Dagenham East" },
  { value: "Dagenham_Heathway", label: "Dagenham Heathway" },
  { value: "Dalston_Junction", label: "Dalston Junction" },
  { value: "Dalston_Kingsland", label: "Dalston Kingsland" },
  { value: "Debden", label: "Debden" },
  { value: "Denmark_Hill", label: "Denmark Hill" },
  { value: "Deptford_Bridge", label: "Deptford Bridge" },
  { value: "Devons_Road", label: "Devons Road" },
  { value: "Dollis_Hill", label: "Dollis Hill" },
  { value: "Drayton_Green", label: "Drayton Green" },
  { value: "Ealing_Broadway", label: "Ealing Broadway" },
  { value: "Ealing_Common", label: "Ealing Common" },
  { value: "Earls_Court", label: "Earls Court" },
  { value: "East_Acton", label: "East Acton" },
  { value: "East_Finchley", label: "East Finchley" },
  { value: "East_Ham_district", label: "East Ham District" },
  { value: "East_Ham_hnc", label: "East Ham Hnc" },
  { value: "East_India", label: "East India" },
  { value: "East_London_zone2-3", label: "East London Zone2-3" },
  { value: "East_Putney", label: "East Putney" },
  { value: "Eastcote_metropolitan", label: "Eastcote Metropolitan" },
  { value: "Eastcote_piccadilly", label: "Eastcote Piccadilly" },
  { value: "Edgware", label: "Edgware" },
  { value: "Edgware_Road_bakerloo", label: "Edgware Road Bakerloo" },
  { value: "Edgware_Road_circle", label: "Edgware Road Circle" },
  { value: "Edmonton_Green", label: "Edmonton Green" },
  { value: "Elephant_And_Castle", label: "Elephant And Castle" },
  { value: "Elm_Park", label: "Elm Park" },
  { value: "Elverson_Road", label: "Elverson Road" },
  { value: "Embankment", label: "Embankment" },
  { value: "Emerson_Park", label: "Emerson Park" },
  { value: "Enfield_Town", label: "Enfield Town" },
  { value: "Epping", label: "Epping" },
  { value: "Euston_Northern_Victoria", label: "Euston Northern Victoria" },
  { value: "Euston_Overground_NR", label: "Euston Overground" },
  { value: "Euston_Square_circle", label: "Euston Square Circle" },
  { value: "Fairlop", label: "Fairlop" },
  { value: "Farringdon_circle", label: "Farringdon Circle" },
  { value: "Farringdon_elizabeth", label: "Farringdon" },
  { value: "Fenchurch_Street", label: "Fenchurch Street" },
  { value: "Finchley_Central", label: "Finchley Central" },
  { value: "Finchley_Road", label: "Finchley Road" },
  { value: "Finchley_Road_and_Frognal", label: "Finchley Road And Frognal" },
  { value: "Finsbury_Park", label: "Finsbury Park" },
  { value: "Forest_Gate", label: "Forest Gate" },
  { value: "Forest_Hill", label: "Forest Hill" },
  { value: "Fulham_Broadway", label: "Fulham Broadway" },
  { value: "Gallions_Reach", label: "Gallions Reach" },
  { value: "Gants_Hill", label: "Gants Hill" },
  { value: "Gidea_Park", label: "Gidea Park" },
  { value: "Gloucester_Road", label: "Gloucester Road" },
  { value: "Golders_Green", label: "Golders Green" },
  { value: "Goldhawk_Road_circle", label: "Goldhawk Road Circle" },
  { value: "Goldhawk_Road_hnc", label: "Goldhawk Road Hnc" },
  { value: "Goodge_Street", label: "Goodge Street" },
  { value: "Goodmayes", label: "Goodmayes" },
  { value: "Gospel_Oak", label: "Gospel Oak" },
  { value: "Grange_Hill", label: "Grange Hill" },
  {
    value: "Great_Portland_Street_circle",
    label: "Great Portland Street Circle",
  },
  { value: "Great_Portland_Street_hnc", label: "Great Portland Street Hnc" },
  {
    value: "Great_Portland_Street_metropolitan",
    label: "Great Portland Street Metropolitan",
  },
  { value: "Green_Park", label: "Green Park" },
  { value: "Greenford", label: "Greenford" },
  { value: "Greenwich", label: "Greenwich" },
  { value: "Gunnersbury", label: "Gunnersbury" },
  { value: "Hackney_Central", label: "Hackney Central" },
  { value: "Hackney_Downs", label: "Hackney Downs" },
  { value: "Hackney_Wick", label: "Hackney Wick" },
  { value: "Haggerston", label: "Haggerston" },
  { value: "Hainault", label: "Hainault" },
  { value: "Hammersmith_circle", label: "Hammersmith Circle" },
  { value: "Hammersmith_district", label: "Hammersmith District" },
  { value: "Hampstead", label: "Hampstead" },
  { value: "Hampstead_Heath", label: "Hampstead Heath" },
  { value: "Hanger_Lane", label: "Hanger Lane" },
  { value: "Hanwell", label: "Hanwell" },
  { value: "Harlesden_bakerloo", label: "Harlesden Bakerloo" },
  { value: "Harlesden_overground", label: "Harlesden Overground" },
  { value: "Harold_Wood", label: "Harold Wood" },
  { value: "Harringay_Green_Lanes", label: "Harringay Green Lanes" },
  { value: "Harrow_and_Wealdstone", label: "Harrow And Wealdstone" },
  { value: "Harrow_on_the_Hill", label: "Harrow On The Hill" },
  { value: "Hatch_End", label: "Hatch End" },
  { value: "Hatton_Cross", label: "Hatton Cross" },
  { value: "Hayes_and_Harlington", label: "Hayes And Harlington" },
  { value: "Headstone_Lane", label: "Headstone Lane" },
  { value: "Heathrow_23", label: "Heathrow 23" },
  { value: "Heathrow_4_elizabeth", label: "Heathrow 4" },
  { value: "Heathrow_4_piccadilly", label: "Heathrow 4 Piccadilly" },
  { value: "Heathrow_5_Piccadilly", label: "Heathrow 5 Piccadilly" },
  { value: "Heathrow_5_elizabeth", label: "Heathrow 5" },
  { value: "Heathrow_Central", label: "Heathrow Central" },
  {
    value: "Heathrow_rail_tunnel_special_fares",
    label: "Heathrow Rail Tunnel Special Fares",
  },
  { value: "Hendon_Central", label: "Hendon Central" },
  { value: "Heron_Quays", label: "Heron Quays" },
  { value: "High_Barnet", label: "High Barnet" },
  {
    value: "High_Street_Kensington_circle",
    label: "High Street Kensington Circle",
  },
  {
    value: "High_Street_Kensington_district",
    label: "High Street Kensington District",
  },
  { value: "Highams_Park", label: "Highams Park" },
  { value: "Highbury_and_Islington", label: "Highbury And Islington" },
  { value: "Highgate", label: "Highgate" },
  { value: "Hillingdon_metropolitan", label: "Hillingdon Metropolitan" },
  { value: "Hillingdon_piccadilly", label: "Hillingdon Piccadilly" },
  { value: "Holborn", label: "Holborn" },
  { value: "Holland_Park", label: "Holland Park" },
  { value: "Holloway_Road", label: "Holloway Road" },
  { value: "Homerton", label: "Homerton" },
  { value: "Honor_Oak_Park", label: "Honor Oak Park" },
  { value: "Hornchurch", label: "Hornchurch" },
  { value: "Hounslow_Central", label: "Hounslow Central" },
  { value: "Hounslow_East", label: "Hounslow East" },
  { value: "Hounslow_West", label: "Hounslow West" },
  { value: "Hoxton", label: "Hoxton" },
  { value: "Hyde_Park_Corner", label: "Hyde Park Corner" },
  { value: "Ickenham", label: "Ickenham" },
  { value: "Ilford", label: "Ilford" },
  { value: "Imperial_Wharf", label: "Imperial Wharf" },
  { value: "Island_Gardens", label: "Island Gardens" },
  { value: "Iver", label: "Iver" },
  { value: "Kennington", label: "Kennington" },
  { value: "Kensal_Green_bakerloo", label: "Kensal Green Bakerloo" },
  { value: "Kensal_Green_overground", label: "Kensal Green Overground" },
  { value: "Kensal_Rise", label: "Kensal Rise" },
  { value: "Kensington_Olympia", label: "Kensington Olympia" },
  { value: "Kentish_Town", label: "Kentish Town" },
  { value: "Kentish_Town_West", label: "Kentish Town West" },
  { value: "Kenton", label: "Kenton" },
  { value: "Kew_Gardens_district", label: "Kew Gardens District" },
  { value: "Kew_Gardens_overground", label: "Kew Gardens Overground" },
  { value: "Kilburn", label: "Kilburn" },
  { value: "Kilburn_High_Road", label: "Kilburn High Road" },
  { value: "Kilburn_Park", label: "Kilburn Park" },
  { value: "King_George_V", label: "King George V" },
  { value: "Kings_Cross_St_Pancras", label: "Kings Cross St Pancras" },
  { value: "Kingsbury", label: "Kingsbury" },
  { value: "Knightsbridge", label: "Knightsbridge" },
  { value: "Ladbroke_Grove_circle", label: "Ladbroke Grove Circle" },
  { value: "Ladbroke_Grove_hnc", label: "Ladbroke Grove Hnc" },
  { value: "Lambeth_North", label: "Lambeth North" },
  { value: "Lancaster_Gate", label: "Lancaster Gate" },
  { value: "Langdon_Park", label: "Langdon Park" },
  { value: "Langley", label: "Langley" },
  { value: "Latimer_Road_circle", label: "Latimer Road Circle" },
  { value: "Latimer_Road_hnc", label: "Latimer Road Hnc" },
  { value: "Leicester_Square", label: "Leicester Square" },
  { value: "Lewisham", label: "Lewisham" },
  { value: "Leyton", label: "Leyton" },
  { value: "Leyton_Midland_Road", label: "Leyton Midland Road" },
  { value: "Leytonstone", label: "Leytonstone" },
  { value: "Leytonstone_High_Road", label: "Leytonstone High Road" },
  { value: "Limehouse", label: "Limehouse" },
  {
    value: "Liverpool_Street_circle_base",
    label: "Liverpool Street Circle Base",
  },
  { value: "Liverpool_Street_circle_top", label: "Liverpool Street" },
  {
    value: "Liverpool_Street_elizabeth_base",
    label: "Liverpool Street Elizabeth Base",
  },
  {
    value: "Liverpool_Street_elizabeth_top",
    label: "Liverpool Street Elizabeth",
  },
  { value: "Liverpool_Street_nr", label: "Liverpool Street" },
  { value: "London_Bridge", label: "London Bridge" },
  { value: "London_City_Airport", label: "London City Airport" },
  { value: "London_Fields", label: "London Fields" },
  { value: "Loughton", label: "Loughton" },
  { value: "Maida_Vale", label: "Maida Vale" },
  { value: "Maidenhead", label: "Maidenhead" },
  { value: "Manor_House", label: "Manor House" },
  { value: "Manor_Park", label: "Manor Park" },
  { value: "Mansion_House_circle", label: "Mansion House Circle" },
  { value: "Mansion_House_district", label: "Mansion House District" },
  { value: "Marble_Arch", label: "Marble Arch" },
  { value: "Maryland", label: "Maryland" },
  { value: "Marylebone", label: "Marylebone" },
  {
    value: "Metropolitan_Piccadilly_stations_shared",
    label: "Metropolitan Piccadilly Stations Shared",
  },
  { value: "Mile_End", label: "Mile End" },
  { value: "Mill_Hill_East", label: "Mill Hill East" },
  { value: "Moor_Park", label: "Moor Park" },
  {
    value: "Moorgate-Liverpool_Street_isi",
    label: "Moorgate-Liverpool Street Isi",
  },
  { value: "Moorgate_base", label: "Moorgate Base" },
  { value: "Moorgate_mid", label: "Moorgate Mid" },
  { value: "Moorgate_top", label: "Moorgate" },
  { value: "Morden", label: "Morden" },
  { value: "Mornington_Crescent", label: "Mornington Crescent" },
  { value: "Mudchute", label: "Mudchute" },
  { value: "Neasden", label: "Neasden" },
  { value: "New_Cross", label: "New Cross" },
  { value: "New_Cross_Gate", label: "New Cross Gate" },
  { value: "Newbury_Park", label: "Newbury Park" },
  { value: "Nine_Elms", label: "Nine Elms" },
  { value: "North_Acton", label: "North Acton" },
  { value: "North_Ealing", label: "North Ealing" },
  { value: "North_Greenwich", label: "North Greenwich" },
  { value: "North_Harrow", label: "North Harrow" },
  { value: "North_Wembley_bakerloo", label: "North Wembley Bakerloo" },
  { value: "North_Wembley_overground", label: "North Wembley Overground" },
  { value: "Northfields", label: "Northfields" },
  { value: "Northolt", label: "Northolt" },
  { value: "Northwick_Park", label: "Northwick Park" },
  { value: "Northwood", label: "Northwood" },
  { value: "Northwood_Hills", label: "Northwood Hills" },
  { value: "Norwood_Junction", label: "Norwood Junction" },
  { value: "Notting_Hill_Gate", label: "Notting Hill Gate" },
  { value: "Oakwood", label: "Oakwood" },
  { value: "Old_Kent_Road", label: "Old Kent Road" },
  { value: "Old_Oak_Common", label: "Old Oak Common" },
  { value: "Old_Street", label: "Old Street" },
  { value: "Osterley", label: "Osterley" },
  { value: "Oval", label: "Oval" },
  { value: "Oxford_Circus", label: "Oxford Circus" },
  {
    value: "Paddington_below_ground_isi",
    label: "Paddington Below Ground Isi",
  },
  { value: "Paddington_deep", label: "Paddington" },
  { value: "Paddington_deep_base", label: "Paddington Deep Base" },
  { value: "Paddington_elizabeth", label: "Paddington" },
  { value: "Paddington_elizabeth_base", label: "Paddington Elizabeth Base" },
  { value: "Paddington_nr", label: "Paddington" },
  { value: "Paddington_surface", label: "Paddington" },
  { value: "Park_Royal", label: "Park Royal" },
  { value: "Parsons_Green", label: "Parsons Green" },
  { value: "Peckham_Rye", label: "Peckham Rye" },
  { value: "Penge_West", label: "Penge West" },
  { value: "Perivale", label: "Perivale" },
  { value: "Piccadilly_Circus", label: "Piccadilly Circus" },
  {
    value: "Piccadilly_Heathrow_divider",
    label: "Piccadilly Heathrow Divider",
  },
  { value: "Pimlico", label: "Pimlico" },
  { value: "Pinner", label: "Pinner" },
  { value: "Plaistow_district", label: "Plaistow District" },
  { value: "Plaistow_hnc", label: "Plaistow Hnc" },
  { value: "Pontoon_Dock", label: "Pontoon Dock" },
  { value: "Poplar", label: "Poplar" },
  { value: "Preston_Road", label: "Preston Road" },
  { value: "Prince_Regent", label: "Prince Regent" },
  { value: "Pudding_Mill_Lane", label: "Pudding Mill Lane" },
  { value: "Putney_Bridge", label: "Putney Bridge" },
  { value: "Queens_Park", label: "Queens Park" },
  { value: "Queens_Road_Peckham", label: "Queens Road Peckham" },
  { value: "Queensbury", label: "Queensbury" },
  { value: "Queensway", label: "Queensway" },
  { value: "Ravenscourt_Park", label: "Ravenscourt Park" },
  { value: "Rayners_Lane", label: "Rayners Lane" },
  { value: "Reading", label: "Reading" },
  { value: "Reading_zone_base", label: "Reading Zone Base" },
  { value: "Rectory_Road", label: "Rectory Road" },
  { value: "Redbridge", label: "Redbridge" },
  { value: "Regents_Park", label: "Regents Park" },
  { value: "Richmond", label: "Richmond" },
  { value: "Rickmansworth", label: "Rickmansworth" },
  { value: "Roding_Valley", label: "Roding Valley" },
  { value: "Romford", label: "Romford" },
  { value: "Rotherhithe", label: "Rotherhithe" },
  { value: "Royal_Albert", label: "Royal Albert" },
  { value: "Royal_Oak_circle", label: "Royal Oak Circle" },
  { value: "Royal_Oak_hnc", label: "Royal Oak Hnc" },
  { value: "Royal_Victoria", label: "Royal Victoria" },
  { value: "Ruislip_Gardens", label: "Ruislip Gardens" },
  { value: "Ruislip_Manor_metropolitan", label: "Ruislip Manor Metropolitan" },
  { value: "Ruislip_Manor_piccadilly", label: "Ruislip Manor Piccadilly" },
  { value: "Ruislip_metropolitan", label: "Ruislip Metropolitan" },
  { value: "Ruislip_piccadilly", label: "Ruislip Piccadilly" },
  { value: "Russell_Square", label: "Russell Square" },
  { value: "Seven_Kings", label: "Seven Kings" },
  { value: "Seven_Sisters", label: "Seven Sisters" },
  { value: "Shadwell", label: "Shadwell" },
  { value: "Shenfield", label: "Shenfield" },
  {
    value: "Shepherds_Bush_Market_circle",
    label: "Shepherds Bush Market Circle",
  },
  { value: "Shepherds_Bush_Market_hnc", label: "Shepherds Bush Market Hnc" },
  { value: "Shepherds_Bush_nr", label: "Shepherds Bush" },
  { value: "Shepherds_Bush_tube", label: "Shepherds Bush" },
  { value: "Shoreditch_High_Street", label: "Shoreditch High Street" },
  { value: "Silver_Street", label: "Silver Street" },
  { value: "Sloane_Square_circle", label: "Sloane Square Circle" },
  { value: "Sloane_Square_district", label: "Sloane Square District" },
  { value: "Slough", label: "Slough" },
  { value: "Snaresbrook", label: "Snaresbrook" },
  { value: "South_Acton", label: "South Acton" },
  { value: "South_Ealing", label: "South Ealing" },
  { value: "South_Greenford", label: "South Greenford" },
  { value: "South_Hampstead", label: "South Hampstead" },
  { value: "South_Harrow", label: "South Harrow" },
  { value: "South_Kensington", label: "South Kensington" },
  { value: "South_Kenton_bakerloo", label: "South Kenton Bakerloo" },
  { value: "South_Kenton_overground", label: "South Kenton Overground" },
  { value: "South_Quay", label: "South Quay" },
  { value: "South_Ruislip", label: "South Ruislip" },
  { value: "South_Tottenham", label: "South Tottenham" },
  { value: "South_Wimbledon", label: "South Wimbledon" },
  { value: "South_Woodford", label: "South Woodford" },
  { value: "Southall", label: "Southall" },
  { value: "Southbury", label: "Southbury" },
  { value: "Southfields", label: "Southfields" },
  { value: "Southgate", label: "Southgate" },
  { value: "Southwark", label: "Southwark" },
  { value: "St_James_Street", label: "St James Street" },
  { value: "St_Jamess_Park_circle", label: "St Jamess Park Circle" },
  { value: "St_Jamess_Park_district", label: "St Jamess Park District" },
  { value: "St_Johns_Wood", label: "St Johns Wood" },
  { value: "St_Pauls", label: "St Pauls" },
  { value: "Stamford_Brook", label: "Stamford Brook" },
  { value: "Stamford_Hill", label: "Stamford Hill" },
  { value: "Stanmore", label: "Stanmore" },
  { value: "Star_Lane", label: "Star Lane" },
  { value: "Stepney_Green_district", label: "Stepney Green District" },
  { value: "Stepney_Green_hnc", label: "Stepney Green Hnc" },
  { value: "Stockwell", label: "Stockwell" },
  { value: "Stoke_Newington", label: "Stoke Newington" },
  { value: "Stonebridge_Park_bakerloo", label: "Stonebridge Park Bakerloo" },
  {
    value: "Stonebridge_Park_overground",
    label: "Stonebridge Park Overground",
  },
  { value: "Stratford", label: "Stratford" },
  { value: "Stratford_High_Street", label: "Stratford High Street" },
  { value: "Stratford_International", label: "Stratford International" },
  { value: "Sudbury_Hill", label: "Sudbury Hill" },
  { value: "Sudbury_Town", label: "Sudbury Town" },
  { value: "Surrey_Canal", label: "Surrey Canal" },
  { value: "Surrey_Quays", label: "Surrey Quays" },
  { value: "Swiss_Cottage", label: "Swiss Cottage" },
  { value: "Sydenham", label: "Sydenham" },
  { value: "Taplow", label: "Taplow" },
  { value: "Temple_circle", label: "Temple Circle" },
  { value: "Temple_district", label: "Temple District" },
  { value: "Theobalds_Grove", label: "Theobalds Grove" },
  { value: "Theydon_Bois", label: "Theydon Bois" },
  { value: "Tooting_Bec", label: "Tooting Bec" },
  { value: "Tooting_Broadway", label: "Tooting Broadway" },
  { value: "Tottenham_Court_Road_cr", label: "Tottenham Court Road" },
  { value: "Tottenham_Hale", label: "Tottenham Hale" },
  { value: "Totteridge_And_Whetstone", label: "Totteridge And Whetstone" },
  { value: "Tower_Gateway", label: "Tower Gateway" },
  { value: "Tower_Hill", label: "Tower Hill" },
  { value: "Tufnell_Park", label: "Tufnell Park" },
  { value: "Turkey_Street", label: "Turkey Street" },
  { value: "Turnham_Green_district", label: "Turnham Green District" },
  { value: "Turnham_Green_piccadilly", label: "Turnham Green Piccadilly" },
  { value: "Turnpike_Lane", label: "Turnpike Lane" },
  { value: "Twyford", label: "Twyford" },
  { value: "Upminster", label: "Upminster" },
  { value: "Upminster_Bridge", label: "Upminster Bridge" },
  { value: "Upney", label: "Upney" },
  { value: "Upper_Holloway", label: "Upper Holloway" },
  { value: "Upton_Park_district", label: "Upton Park District" },
  { value: "Upton_Park_hnc", label: "Upton Park Hnc" },
  {
    value: "Uxbridge-Rayner_Lane_divider",
    label: "Uxbridge-Rayner Lane Divider",
  },
  { value: "Uxbridge_metropolitan", label: "Uxbridge Metropolitan" },
  { value: "Uxbridge_piccadilly", label: "Uxbridge Piccadilly" },
  { value: "Vauxhall", label: "Vauxhall" },
  { value: "Victoria", label: "Victoria" },
  { value: "Victoria_Coach_Station", label: "Victoria Coach Station" },
  { value: "Walthamstow_Central", label: "Walthamstow Central" },
  { value: "Walthamstow_Queens_Road", label: "Walthamstow Queens Road" },
  { value: "Wandsworth_Road", label: "Wandsworth Road" },
  { value: "Wanstead", label: "Wanstead" },
  { value: "Wanstead_Park", label: "Wanstead Park" },
  { value: "Wapping", label: "Wapping" },
  { value: "Warren_Street", label: "Warren Street" },
  { value: "Warwick_Avenue", label: "Warwick Avenue" },
  { value: "Waterloo", label: "Waterloo" },
  { value: "Watford", label: "Watford" },
  { value: "Watford_High_Street", label: "Watford High Street" },
  { value: "Watford_Junction", label: "Watford Junction" },
  { value: "Wembley_Central", label: "Wembley Central" },
  { value: "Wembley_Park", label: "Wembley Park" },
  { value: "West_Acton", label: "West Acton" },
  { value: "West_Brompton", label: "West Brompton" },
  { value: "West_Croydon", label: "West Croydon" },
  { value: "West_Drayton", label: "West Drayton" },
  { value: "West_Ealing", label: "West Ealing" },
  { value: "West_Finchley", label: "West Finchley" },
  { value: "West_Ham", label: "West Ham" },
  { value: "West_Hampstead", label: "West Hampstead" },
  { value: "West_Harrow", label: "West Harrow" },
  { value: "West_India_Quay", label: "West India Quay" },
  { value: "West_Kensington", label: "West Kensington" },
  { value: "West_Ruislip", label: "West Ruislip" },
  { value: "West_Silvertown", label: "West Silvertown" },
  { value: "Westbourne_Park_circle", label: "Westbourne Park Circle" },
  { value: "Westbourne_Park_hnc", label: "Westbourne Park Hnc" },
  { value: "Westferry", label: "Westferry" },
  { value: "Westminster", label: "Westminster" },
  { value: "White_City", label: "White City" },
  { value: "White_Hart_Lane", label: "White Hart Lane" },
  { value: "Whitechapel", label: "Whitechapel" },
  { value: "Willesden_Green", label: "Willesden Green" },
  { value: "Willesden_Junction", label: "Willesden Junction" },
  { value: "Wimbledon", label: "Wimbledon" },
  { value: "Wimbledon_Park", label: "Wimbledon Park" },
  { value: "Wood_Green", label: "Wood Green" },
  { value: "Wood_Lane", label: "Wood Lane" },
  { value: "Wood_Street", label: "Wood Street" },
  { value: "Woodford", label: "Woodford" },
  { value: "Woodgrange_Park", label: "Woodgrange Park" },
  { value: "Woodside_Park", label: "Woodside Park" },
  { value: "Woolwich", label: "Woolwich" },
  { value: "Woolwich_Arsenal", label: "Woolwich Arsenal" },
];
