export type Station = {
  value: string;
  label: string;
};

export const stations: Station[] = [
  { value: "AETRAM", label: "AETRAM" },
  { value: "Abbey_Road", label: "Abbey Road" },
  { value: "Abbey_Wood", label: "Abbey Wood" },
  { value: "Acton_Central", label: "Acton Central" },
  { value: "Acton_Main_Line", label: "Acton Main Line" },
  { value: "Acton_Town", label: "Acton Town" },
  { value: "Aldgate", label: "Aldgate" },
  { value: "Aldgate_East", label: "Aldgate East" },
  { value: "All_Saints", label: "All Saints" },
  { value: "Alperton", label: "Alperton" },
  { value: "Amersham", label: "Amersham" },
  { value: "Anerley", label: "Anerley" },
  { value: "Angel", label: "Angel" },
  { value: "Archway", label: "Archway" },
  { value: "Archway_zone", label: "Archway Zone" },
  { value: "Arnos_Grove", label: "Arnos Grove" },
  { value: "Arsenal", label: "Arsenal" },
  { value: "Baker_Street", label: "Baker Street" },
  {
    value: "Bakerloo_Lioness_shared_stations",
    label: "Bakerloo Lioness Shared Stations",
  },
  { value: "Bakerloo_line_blink", label: "Bakerloo Line Blink" },
  {
    value: "Bakerloo_line_extension_blink",
    label: "Bakerloo Line Extension Blink",
  },
  { value: "Bakerloo_line_off", label: "Bakerloo Line Off" },
  { value: "Bakerloo_line_route", label: "Bakerloo Line Route" },
  {
    value: "Bakerloo_line_route_extension",
    label: "Bakerloo Line Route Extension",
  },
  {
    value: "Bakerloo_line_route_extension_base",
    label: "Bakerloo Line Route Extension Base",
  },
  { value: "Bakerloo_line_stations", label: "Bakerloo Line Stations" },
  { value: "Balham", label: "Balham" },
  { value: "Bank_Monument_hub", label: "Bank Monument Hub" },
  { value: "Barbican", label: "Barbican" },
  { value: "Barbican_Farringdon_osi", label: "Barbican Farringdon Osi" },
  { value: "Barking", label: "Barking" },
  { value: "Barking_Riverside", label: "Barking Riverside" },
  { value: "Barkingside", label: "Barkingside" },
  { value: "Barons_Court_district", label: "Barons Court District" },
  { value: "Barons_Court_piccadilly", label: "Barons Court Piccadilly" },
  { value: "Battersea_Park", label: "Battersea Park" },
  { value: "Battersea_Park_osi", label: "Battersea Park Osi" },
  { value: "Battersea_Power_Station", label: "Battersea Power Station" },
  { value: "Bayswater_circle", label: "Bayswater Circle" },
  { value: "Bayswater_district", label: "Bayswater District" },
  { value: "Beckton", label: "Beckton" },
  { value: "Beckton_Park", label: "Beckton Park" },
  { value: "Becontree", label: "Becontree" },
  { value: "Belsize_Park", label: "Belsize Park" },
  { value: "Bermondsey", label: "Bermondsey" },
  { value: "Bethnal_Green", label: "Bethnal Green" },
  { value: "Bethnal_Green_central", label: "Bethnal Green Central" },
  { value: "Blackfriars", label: "Blackfriars" },
  { value: "Blackhorse_Road", label: "Blackhorse Road" },
  { value: "Blackhorse_Road_validator", label: "Blackhorse Road Validator" },
  { value: "Blackwall", label: "Blackwall" },
  { value: "Bond_Street", label: "Bond Street" },
  {
    value: "Bond_Street_Oxford_Circus_osi",
    label: "Bond Street Oxford Circus Osi",
  },
  { value: "Borough", label: "Borough" },
  { value: "Boston_Manor", label: "Boston Manor" },
  { value: "Bounds_Green", label: "Bounds Green" },
  { value: "Bounds_Green_zone", label: "Bounds Green Zone" },
  { value: "Bow_Church", label: "Bow Church" },
  { value: "Bow_Road", label: "Bow Road" },
  { value: "Bow_osi", label: "Bow Osi" },
  { value: "Brent_Cross", label: "Brent Cross" },
  { value: "Brentwood", label: "Brentwood" },
  { value: "Brixton", label: "Brixton" },
  { value: "Brockley", label: "Brockley" },
  { value: "Brondesbury", label: "Brondesbury" },
  { value: "Brondesbury_Kilburn_osi", label: "Brondesbury Kilburn Osi" },
  { value: "Brondesbury_Park", label: "Brondesbury Park" },
  { value: "Bruce_Grove", label: "Bruce Grove" },
  { value: "Buckhurst_Hill", label: "Buckhurst Hill" },
  { value: "Burgess_Park", label: "Burgess Park" },
  { value: "Burnham", label: "Burnham" },
  { value: "Burnt_Oak", label: "Burnt Oak" },
  { value: "Bush_Hill_Park", label: "Bush Hill Park" },
  { value: "Bushey", label: "Bushey" },
  { value: "CONTf", label: "CONTf" },
  { value: "Caledonian_Road", label: "Caledonian Road" },
  {
    value: "Caledonian_Road_and_Barnsbury",
    label: "Caledonian Road And Barnsbury",
  },
  { value: "Cambridge_Heath", label: "Cambridge Heath" },
  { value: "Camden_Road", label: "Camden Road" },
  { value: "Camden_Town", label: "Camden Town" },
  { value: "Canada_Water", label: "Canada Water" },
  { value: "Canada_Water_validator", label: "Canada Water Validator" },
  { value: "Canary_Wharf_dlr", label: "Canary Wharf Dlr" },
  { value: "Canary_Wharf_elizabeth", label: "Canary Wharf" },
  { value: "Canary_Wharf_jubilee", label: "Canary Wharf Jubilee" },
  { value: "Canning_Town", label: "Canning Town" },
  { value: "Cannon_Street", label: "Cannon Street" },
  { value: "Canonbury", label: "Canonbury" },
  { value: "Canons_Park", label: "Canons Park" },
  { value: "Carpenders_Park", label: "Carpenders Park" },
  { value: "Castle_Bar_Park", label: "Castle Bar Park" },
  { value: "Castle_Green", label: "Castle Green" },
  { value: "Central_line_blink", label: "Central Line Blink" },
  { value: "Central_line_off", label: "Central Line Off" },
  { value: "Central_line_route", label: "Central Line Route" },
  { value: "Central_line_route_over", label: "Central Line Route Over" },
  { value: "Central_line_stations", label: "Central Line Stations" },
  { value: "Chadwell_Heath", label: "Chadwell Heath" },
  { value: "Chalfont_and_Latimer", label: "Chalfont And Latimer" },
  { value: "Chalk_Farm", label: "Chalk Farm" },
  { value: "Chancery_Lane", label: "Chancery Lane" },
  { value: "Charing_Cross", label: "Charing Cross" },
  { value: "Chesham", label: "Chesham" },
  { value: "Cheshunt", label: "Cheshunt" },
  { value: "Chigwell", label: "Chigwell" },
  { value: "Chingford", label: "Chingford" },
  { value: "Chiswick_Park", label: "Chiswick Park" },
  { value: "Chorleywood", label: "Chorleywood" },
  { value: "Circle_line_blink", label: "Circle Line Blink" },
  { value: "Circle_line_off", label: "Circle Line Off" },
  { value: "Circle_line_route", label: "Circle Line Route" },
  { value: "Circle_line_stations", label: "Circle Line Stations" },
  { value: "Clapham_Common", label: "Clapham Common" },
  { value: "Clapham_High_Street", label: "Clapham High Street" },
  { value: "Clapham_Junction", label: "Clapham Junction" },
  { value: "Clapham_Junction_validator", label: "Clapham Junction Validator" },
  { value: "Clapham_North", label: "Clapham North" },
  { value: "Clapham_South", label: "Clapham South" },
  { value: "Clapham_South_zone", label: "Clapham South Zone" },
  { value: "Clapton", label: "Clapton" },
  { value: "Clapton_zone", label: "Clapton Zone" },
  { value: "Cockfosters", label: "Cockfosters" },
  { value: "Colindale", label: "Colindale" },
  { value: "Colliers_Wood", label: "Colliers Wood" },
  { value: "Covent_Garden", label: "Covent Garden" },
  { value: "Crossharbour", label: "Crossharbour" },
  { value: "Crouch_Hill", label: "Crouch Hill" },
  { value: "Croxley", label: "Croxley" },
  { value: "Crystal_Palace", label: "Crystal Palace" },
  { value: "Crystal_Palace_zone", label: "Crystal Palace Zone" },
  { value: "Custom_House_for_ExCeL", label: "Custom House For ExCeL" },
  {
    value: "Cutty_Sark_for_Maritime_Greenwich",
    label: "Cutty Sark For Maritime Greenwich",
  },
  { value: "Cyprus", label: "Cyprus" },
  { value: "DLR_blink", label: "DLR Blink" },
  { value: "DLR_off", label: "DLR Off" },
  { value: "DLR_over_blink", label: "DLR Over Blink" },
  { value: "DLR_route_over", label: "DLR Route Over" },
  { value: "DLR_route_stripe_over", label: "DLR Route Stripe Over" },
  { value: "DLR_routes", label: "DLR Routes" },
  { value: "DLR_routes_stripe", label: "DLR Routes Stripe" },
  { value: "Dagenham_East", label: "Dagenham East" },
  { value: "Dagenham_Heathway", label: "Dagenham Heathway" },
  { value: "Dalston_Junction", label: "Dalston Junction" },
  { value: "Dalston_Kingsland", label: "Dalston Kingsland" },
  { value: "Debden", label: "Debden" },
  { value: "Denmark_Hill", label: "Denmark Hill" },
  { value: "Deptford_Bridge", label: "Deptford Bridge" },
  { value: "Devons_Road", label: "Devons Road" },
  { value: "District_Olympia_branch", label: "District Olympia Branch" },
  {
    value: "District_Olympia_branch_blink",
    label: "District Olympia Branch Blink",
  },
  {
    value: "District_Olympia_branch_stripe",
    label: "District Olympia Branch Stripe",
  },
  { value: "District_line_blink", label: "District Line Blink" },
  { value: "District_line_off", label: "District Line Off" },
  { value: "District_line_route", label: "District Line Route" },
  { value: "District_line_stations", label: "District Line Stations" },
  {
    value: "Docklands_Light_Railway_stations",
    label: "Docklands Light Railway Stations",
  },
  { value: "Dollis_Hill", label: "Dollis Hill" },
  { value: "Drayton_Green", label: "Drayton Green" },
  { value: "Ealing_Broadway", label: "Ealing Broadway" },
  { value: "Ealing_Common", label: "Ealing Common" },
  { value: "Earls_Court", label: "Earls Court" },
  { value: "Earls_Court_zone", label: "Earls Court Zone" },
  { value: "East_Acton", label: "East Acton" },
  { value: "East_Finchley", label: "East Finchley" },
  { value: "East_Ham_district", label: "East Ham District" },
  { value: "East_Ham_hnc", label: "East Ham Hnc" },
  { value: "East_Ham_zone", label: "East Ham Zone" },
  { value: "East_India", label: "East India" },
  { value: "East_Putney", label: "East Putney" },
  { value: "East_Putney_zone", label: "East Putney Zone" },
  {
    value: "East_and_South_London_line_off",
    label: "East And South London Line Off",
  },
  { value: "Eastcote_metropolitan", label: "Eastcote Metropolitan" },
  { value: "Eastcote_piccadilly", label: "Eastcote Piccadilly" },
  { value: "Edgware", label: "Edgware" },
  { value: "Edgware_Road_bakerloo", label: "Edgware Road Bakerloo" },
  { value: "Edgware_Road_circle", label: "Edgware Road Circle" },
  {
    value: "Edgware_line_Battersea_extension_blink",
    label: "Edgware Line Battersea Extension Blink",
  },
  { value: "Edgware_line_blink", label: "Edgware Line Blink" },
  { value: "Edgware_line_off", label: "Edgware Line Off" },
  { value: "Edgware_line_route", label: "Edgware Line Route" },
  { value: "Edgware_line_stations", label: "Edgware Line Stations" },
  { value: "Edmonton_Green", label: "Edmonton Green" },
  { value: "Elephant_And_Castle", label: "Elephant And Castle" },
  { value: "Elephant_And_Castle_zone", label: "Elephant And Castle Zone" },
  { value: "Elizabeth_blink", label: "Elizabeth Blink" },
  {
    value: "Elizabeth_branch_east_stripe",
    label: "Elizabeth Branch East Stripe",
  },
  {
    value: "Elizabeth_line_beyond_eastern_boundary",
    label: "Elizabeth Line Beyond Eastern Boundary",
  },
  { value: "Elizabeth_line_branch_east", label: "Elizabeth Line Branch East" },
  { value: "Elizabeth_line_stations", label: "Elizabeth Line Stations" },
  { value: "Elizabeth_off", label: "Elizabeth Off" },
  { value: "Elizabeth_route", label: "Elizabeth Route" },
  { value: "Elizabeth_route_main", label: "Elizabeth Route Main" },
  { value: "Elizabeth_stripe", label: "Elizabeth Stripe" },
  { value: "Elm_Park", label: "Elm Park" },
  { value: "Elverson_Road", label: "Elverson Road" },
  { value: "Embankment", label: "Embankment" },
  { value: "Emerson_Park", label: "Emerson Park" },
  { value: "Enfield_Town", label: "Enfield Town" },
  { value: "Epping", label: "Epping" },
  { value: "Euston_Northern_Victoria", label: "Euston Northern Victoria" },
  { value: "Euston_Overground_NR", label: "Euston Overground" },
  { value: "Euston_Square_circle", label: "Euston Square Circle" },
  { value: "Euston_osi", label: "Euston Osi" },
  { value: "Fairlop", label: "Fairlop" },
  { value: "Farringdon_circle", label: "Farringdon Circle" },
  { value: "Farringdon_elizabeth", label: "Farringdon" },
  { value: "Fenchurch_Street", label: "Fenchurch Street" },
  { value: "Fenchurch_Street_osi_base", label: "Fenchurch Street Osi Base" },
  { value: "Finchley_Central", label: "Finchley Central" },
  { value: "Finchley_Road", label: "Finchley Road" },
  { value: "Finchley_Road_and_Frognal", label: "Finchley Road And Frognal" },
  { value: "Finsbury_Park", label: "Finsbury Park" },
  { value: "Forest_Gate", label: "Forest Gate" },
  { value: "Forest_Hill", label: "Forest Hill" },
  { value: "Fulham_Broadway", label: "Fulham Broadway" },
  { value: "Gallions_Reach", label: "Gallions Reach" },
  { value: "Gants_Hill", label: "Gants Hill" },
  { value: "Gatwick_Express_route", label: "Gatwick Express Route" },
  { value: "Gidea_Park", label: "Gidea Park" },
  { value: "Gloucester_Road", label: "Gloucester Road" },
  { value: "Golders_Green", label: "Golders Green" },
  { value: "Goldhawk_Road_circle", label: "Goldhawk Road Circle" },
  { value: "Goldhawk_Road_hnc", label: "Goldhawk Road Hnc" },
  { value: "Goodge_Street", label: "Goodge Street" },
  { value: "Goodmayes", label: "Goodmayes" },
  { value: "Gospel_Oak", label: "Gospel Oak" },
  { value: "Gospel_Oak_validator", label: "Gospel Oak Validator" },
  { value: "Grange_Hill", label: "Grange Hill" },
  {
    value: "Great_Portland_Street_circle",
    label: "Great Portland Street Circle",
  },
  { value: "Great_Portland_Street_hnc", label: "Great Portland Street Hnc" },
  {
    value: "Great_Portland_Street_metropolitan",
    label: "Great Portland Street Metropolitan",
  },
  { value: "Green_Park", label: "Green Park" },
  { value: "Greenford", label: "Greenford" },
  {
    value: "Greenford_Branch_line_stations",
    label: "Greenford Branch Line Stations",
  },
  { value: "Greenwich", label: "Greenwich" },
  { value: "Gunnersbury", label: "Gunnersbury" },
  { value: "Gunnersbury_validator", label: "Gunnersbury Validator" },
  { value: "Hackney_Central", label: "Hackney Central" },
  { value: "Hackney_Downs", label: "Hackney Downs" },
  { value: "Hackney_Wick", label: "Hackney Wick" },
  { value: "Hackney_validator", label: "Hackney Validator" },
  { value: "Haggerston", label: "Haggerston" },
  { value: "Hainault", label: "Hainault" },
  {
    value: "Hammersmith_And_City_line_stations",
    label: "Hammersmith And City Line Stations",
  },
  {
    value: "Hammersmith_and_City_line_blink",
    label: "Hammersmith And City Line Blink",
  },
  {
    value: "Hammersmith_and_City_line_off",
    label: "Hammersmith And City Line Off",
  },
  {
    value: "Hammersmith_and_City_line_route",
    label: "Hammersmith And City Line Route",
  },
  { value: "Hammersmith_circle", label: "Hammersmith Circle" },
  { value: "Hammersmith_district", label: "Hammersmith District" },
  { value: "Hampstead", label: "Hampstead" },
  { value: "Hampstead_Heath", label: "Hampstead Heath" },
  { value: "Hampstead_zone", label: "Hampstead Zone" },
  { value: "Hanger_Lane", label: "Hanger Lane" },
  { value: "Hanger_Lane_Park_Royal_osi", label: "Hanger Lane Park Royal Osi" },
  { value: "Hanwell", label: "Hanwell" },
  { value: "Harlesden_bakerloo", label: "Harlesden Bakerloo" },
  { value: "Harlesden_overground", label: "Harlesden Overground" },
  { value: "Harold_Wood", label: "Harold Wood" },
  { value: "Harringay_Green_Lanes", label: "Harringay Green Lanes" },
  { value: "Harrow_and_Wealdstone", label: "Harrow And Wealdstone" },
  { value: "Harrow_on_the_Hill", label: "Harrow On The Hill" },
  { value: "Hatch_End", label: "Hatch End" },
  { value: "Hatton_Cross", label: "Hatton Cross" },
  { value: "Hatton_Cross_zone", label: "Hatton Cross Zone" },
  { value: "Hayes_and_Harlington", label: "Hayes And Harlington" },
  { value: "Headstone_Lane", label: "Headstone Lane" },
  { value: "Heathrow_23", label: "Heathrow 23" },
  { value: "Heathrow_4_elizabeth", label: "Heathrow 4" },
  { value: "Heathrow_4_piccadilly", label: "Heathrow 4 Piccadilly" },
  { value: "Heathrow_5_Piccadilly", label: "Heathrow 5 Piccadilly" },
  { value: "Heathrow_5_elizabeth", label: "Heathrow 5" },
  { value: "Heathrow_5_separator", label: "Heathrow 5 Separator" },
  { value: "Heathrow_Central", label: "Heathrow Central" },
  {
    value: "Heathrow_rail_tunnel_special_fares",
    label: "Heathrow Rail Tunnel Special Fares",
  },
  { value: "Hendon_Central", label: "Hendon Central" },
  { value: "Hendon_Central_zone", label: "Hendon Central Zone" },
  { value: "Heron_Quays", label: "Heron Quays" },
  { value: "High_Barnet", label: "High Barnet" },
  {
    value: "High_Street_Kensington_circle",
    label: "High Street Kensington Circle",
  },
  {
    value: "High_Street_Kensington_district",
    label: "High Street Kensington District",
  },
  { value: "Highams_Park", label: "Highams Park" },
  { value: "Highbury_and_Islington", label: "Highbury And Islington" },
  {
    value: "Highbury_and_Islington_validator",
    label: "Highbury And Islington Validator",
  },
  { value: "Highgate", label: "Highgate" },
  { value: "Hillingdon_metropolitan", label: "Hillingdon Metropolitan" },
  { value: "Hillingdon_piccadilly", label: "Hillingdon Piccadilly" },
  { value: "Holborn", label: "Holborn" },
  { value: "Holland_Park", label: "Holland Park" },
  { value: "Holloway_Road", label: "Holloway Road" },
  { value: "Homerton", label: "Homerton" },
  { value: "Honor_Oak_Park", label: "Honor Oak Park" },
  { value: "Hornchurch", label: "Hornchurch" },
  { value: "Hounslow_Central", label: "Hounslow Central" },
  { value: "Hounslow_East", label: "Hounslow East" },
  { value: "Hounslow_West", label: "Hounslow West" },
  { value: "Hoxton", label: "Hoxton" },
  { value: "Hoxton_zone", label: "Hoxton Zone" },
  { value: "Hyde_Park_Corner", label: "Hyde Park Corner" },
  { value: "Ickenham", label: "Ickenham" },
  { value: "Ilford", label: "Ilford" },
  { value: "Imperial_Wharf", label: "Imperial Wharf" },
  { value: "Island_Gardens", label: "Island Gardens" },
  { value: "Iver", label: "Iver" },
  { value: "Jubilee_line_blink", label: "Jubilee Line Blink" },
  { value: "Jubilee_line_off", label: "Jubilee Line Off" },
  { value: "Jubilee_line_route", label: "Jubilee Line Route" },
  { value: "Jubilee_line_stations", label: "Jubilee Line Stations" },
  { value: "Kennington", label: "Kennington" },
  { value: "Kensal_Green_bakerloo", label: "Kensal Green Bakerloo" },
  { value: "Kensal_Green_overground", label: "Kensal Green Overground" },
  { value: "Kensal_Rise", label: "Kensal Rise" },
  { value: "Kensington_Olympia", label: "Kensington Olympia" },
  {
    value: "Kensington_Olympia_validator",
    label: "Kensington Olympia Validator",
  },
  { value: "Kentish_Town", label: "Kentish Town" },
  { value: "Kentish_Town_West", label: "Kentish Town West" },
  { value: "Kenton", label: "Kenton" },
  { value: "Kenton_Northwick_Park_osi", label: "Kenton Northwick Park Osi" },
  { value: "Kew_Gardens_district", label: "Kew Gardens District" },
  { value: "Kew_Gardens_overground", label: "Kew Gardens Overground" },
  { value: "Kew_Gardens_zone", label: "Kew Gardens Zone" },
  { value: "Kilburn", label: "Kilburn" },
  { value: "Kilburn_High_Road", label: "Kilburn High Road" },
  { value: "Kilburn_Park", label: "Kilburn Park" },
  { value: "King_George_V", label: "King George V" },
  { value: "Kings_Cross_St_Pancras", label: "Kings Cross St Pancras" },
  { value: "Kingsbury", label: "Kingsbury" },
  { value: "Knightsbridge", label: "Knightsbridge" },
  { value: "Ladbroke_Grove_circle", label: "Ladbroke Grove Circle" },
  { value: "Ladbroke_Grove_hnc", label: "Ladbroke Grove Hnc" },
  { value: "Lambeth_North", label: "Lambeth North" },
  { value: "Lancaster_Gate", label: "Lancaster Gate" },
  { value: "Langdon_Park", label: "Langdon Park" },
  { value: "Langley", label: "Langley" },
  { value: "Latimer_Road_circle", label: "Latimer Road Circle" },
  { value: "Latimer_Road_hnc", label: "Latimer Road Hnc" },
  { value: "Leicester_Square", label: "Leicester Square" },
  { value: "Lewisham", label: "Lewisham" },
  { value: "Leyton", label: "Leyton" },
  { value: "Leyton_Midland_Road", label: "Leyton Midland Road" },
  { value: "Leytonstone", label: "Leytonstone" },
  { value: "Leytonstone_High_Road", label: "Leytonstone High Road" },
  { value: "Leytonstone_High_Road_osi", label: "Leytonstone High Road Osi" },
  { value: "Leytonstone_zone", label: "Leytonstone Zone" },
  { value: "Liberty_line_blink", label: "Liberty Line Blink" },
  { value: "Liberty_line_route", label: "Liberty Line Route" },
  { value: "Liberty_line_route_stripe", label: "Liberty Line Route Stripe" },
  { value: "Liberty_line_station", label: "Liberty Line Station" },
  { value: "Limehouse", label: "Limehouse" },
  { value: "Lioness_line_blink", label: "Lioness Line Blink" },
  { value: "Lioness_line_blink_over", label: "Lioness Line Blink Over" },
  { value: "Lioness_line_off", label: "Lioness Line Off" },
  { value: "Lioness_line_over_stripe", label: "Lioness Line Over Stripe" },
  { value: "Lioness_line_route", label: "Lioness Line Route" },
  { value: "Lioness_line_route_over", label: "Lioness Line Route Over" },
  { value: "Lioness_line_stations", label: "Lioness Line Stations" },
  { value: "Lioness_line_stripe", label: "Lioness Line Stripe" },
  {
    value: "Liverpool_Street_Moorgate_osi",
    label: "Liverpool Street Moorgate Osi",
  },
  {
    value: "Liverpool_Street_circle_base",
    label: "Liverpool Street Circle Base",
  },
  { value: "Liverpool_Street_circle_top", label: "Liverpool Street" },
  {
    value: "Liverpool_Street_elizabeth_base",
    label: "Liverpool Street Elizabeth Base",
  },
  {
    value: "Liverpool_Street_elizabeth_top",
    label: "Liverpool Street Elizabeth",
  },
  { value: "Liverpool_Street_nr", label: "Liverpool Street" },
  { value: "London_Bridge", label: "London Bridge" },
  { value: "London_City_Airport", label: "London City Airport" },
  { value: "London_Fields", label: "London Fields" },
  { value: "Loughton", label: "Loughton" },
  { value: "Maida_Vale", label: "Maida Vale" },
  { value: "Maidenhead", label: "Maidenhead" },
  { value: "Manor_House", label: "Manor House" },
  { value: "Manor_House_zone", label: "Manor House Zone" },
  { value: "Manor_Park", label: "Manor Park" },
  { value: "Mansion_House_circle", label: "Mansion House Circle" },
  { value: "Mansion_House_district", label: "Mansion House District" },
  { value: "Marble_Arch", label: "Marble Arch" },
  { value: "Maryland", label: "Maryland" },
  { value: "Marylebone", label: "Marylebone" },
  {
    value: "Metropolitan_Piccadilly_stations_shared",
    label: "Metropolitan Piccadilly Stations Shared",
  },
  { value: "Metropolitan_line_blink", label: "Metropolitan Line Blink" },
  { value: "Metropolitan_line_off", label: "Metropolitan Line Off" },
  { value: "Metropolitan_line_route", label: "Metropolitan Line Route" },
  { value: "Metropolitan_line_stations", label: "Metropolitan Line Stations" },
  { value: "Mildmay_line_stations", label: "Mildmay Line Stations" },
  { value: "Mildmay_lines_route", label: "Mildmay Lines Route" },
  { value: "Mildmay_lines_route_stripe", label: "Mildmay Lines Route Stripe" },
  { value: "Mile_End", label: "Mile End" },
  { value: "Mill_Hill_East", label: "Mill Hill East" },
  { value: "Moor_Park", label: "Moor Park" },
  { value: "Moor_Park_zone", label: "Moor Park Zone" },
  { value: "Moorgate_base", label: "Moorgate Base" },
  { value: "Moorgate_mid", label: "Moorgate Mid" },
  { value: "Moorgate_top", label: "Moorgate" },
  { value: "Morden", label: "Morden" },
  { value: "Mornington_Crescent", label: "Mornington Crescent" },
  { value: "Mudchute", label: "Mudchute" },
  {
    value: "Multiple_interchanges_group",
    label: "Multiple Interchanges Group",
  },
  { value: "National_Rail_continuation", label: "National Rail Continuation" },
  { value: "Neasden", label: "Neasden" },
  { value: "New_Cross", label: "New Cross" },
  { value: "New_Cross_Gate", label: "New Cross Gate" },
  { value: "New_Cross_osi", label: "New Cross Osi" },
  { value: "Newbury_Park", label: "Newbury Park" },
  { value: "Nine_Elms", label: "Nine Elms" },
  { value: "North_Acton", label: "North Acton" },
  { value: "North_Acton_zone", label: "North Acton Zone" },
  { value: "North_Ealing", label: "North Ealing" },
  { value: "North_Greenwich", label: "North Greenwich" },
  { value: "North_Harrow", label: "North Harrow" },
  { value: "North_London_line_route", label: "North London Line Route" },
  { value: "North_Wembley_bakerloo", label: "North Wembley Bakerloo" },
  { value: "North_Wembley_overground", label: "North Wembley Overground" },
  {
    value: "North_and_West_London_line_off",
    label: "North And West London Line Off",
  },
  {
    value: "North_and_West_London_lines_blink",
    label: "North And West London Lines Blink",
  },
  { value: "Northern_line_blink", label: "Northern Line Blink" },
  { value: "Northern_line_off", label: "Northern Line Off" },
  { value: "Northern_line_route", label: "Northern Line Route" },
  { value: "Northern_line_stations", label: "Northern Line Stations" },
  { value: "Northfields", label: "Northfields" },
  { value: "Northolt", label: "Northolt" },
  { value: "Northwick_Park", label: "Northwick Park" },
  { value: "Northwood", label: "Northwood" },
  { value: "Northwood_Hills", label: "Northwood Hills" },
  { value: "Norwood_Junction", label: "Norwood Junction" },
  { value: "Notting_Hill_Gate", label: "Notting Hill Gate" },
  { value: "Notting_Hill_Gate_zone", label: "Notting Hill Gate Zone" },
  { value: "Oakwood", label: "Oakwood" },
  { value: "Old_Kent_Road", label: "Old Kent Road" },
  { value: "Old_Oak_Common", label: "Old Oak Common" },
  { value: "Old_Street", label: "Old Street" },
  { value: "Osterley", label: "Osterley" },
  { value: "Oval", label: "Oval" },
  { value: "Oxford_Circus", label: "Oxford Circus" },
  {
    value: "Paddington_below_ground_isi",
    label: "Paddington Below Ground Isi",
  },
  { value: "Paddington_deep", label: "Paddington" },
  { value: "Paddington_deep_base", label: "Paddington Deep Base" },
  { value: "Paddington_elizabeth", label: "Paddington" },
  { value: "Paddington_elizabeth_base", label: "Paddington Elizabeth Base" },
  { value: "Paddington_nr", label: "Paddington" },
  { value: "Paddington_osi", label: "Paddington Osi" },
  { value: "Paddington_osi_base", label: "Paddington Osi Base" },
  { value: "Paddington_surface", label: "Paddington" },
  { value: "Park_Royal", label: "Park Royal" },
  { value: "Parsons_Green", label: "Parsons Green" },
  { value: "Peckham_Rye", label: "Peckham Rye" },
  { value: "Penge_West", label: "Penge West" },
  { value: "Perivale", label: "Perivale" },
  { value: "Piccadilly_Circus", label: "Piccadilly Circus" },
  {
    value: "Piccadilly_Heathrow_divider",
    label: "Piccadilly Heathrow Divider",
  },
  { value: "Piccadilly_line_blink", label: "Piccadilly Line Blink" },
  { value: "Piccadilly_line_off", label: "Piccadilly Line Off" },
  { value: "Piccadilly_line_route", label: "Piccadilly Line Route" },
  { value: "Piccadilly_line_stations", label: "Piccadilly Line Stations" },
  { value: "Pimlico", label: "Pimlico" },
  { value: "Pinner", label: "Pinner" },
  { value: "Plaistow_district", label: "Plaistow District" },
  { value: "Plaistow_hnc", label: "Plaistow Hnc" },
  { value: "Pontoon_Dock", label: "Pontoon Dock" },
  { value: "Poplar", label: "Poplar" },
  { value: "Portobello_Central", label: "Portobello Central" },
  { value: "Preston_Road", label: "Preston Road" },
  { value: "Prince_Regent", label: "Prince Regent" },
  { value: "Pudding_Mill_Lane", label: "Pudding Mill Lane" },
  { value: "Putney_Bridge", label: "Putney Bridge" },
  { value: "Queens_Park", label: "Queens Park" },
  { value: "Queens_Road_Peckham", label: "Queens Road Peckham" },
  { value: "Queensbury", label: "Queensbury" },
  { value: "Queensway", label: "Queensway" },
  { value: "Ravenscourt_Park", label: "Ravenscourt Park" },
  { value: "Rayners_Lane", label: "Rayners Lane" },
  { value: "Rayners_Lane_validator", label: "Rayners Lane Validator" },
  { value: "Reading", label: "Reading" },
  { value: "Reading_zone_base", label: "Reading Zone Base" },
  { value: "Rectory_Road", label: "Rectory Road" },
  { value: "Redbridge", label: "Redbridge" },
  { value: "Regents_Park", label: "Regents Park" },
  { value: "Richmond", label: "Richmond" },
  { value: "Richmond_validator", label: "Richmond Validator" },
  { value: "Rickmansworth", label: "Rickmansworth" },
  { value: "Roding_Valley", label: "Roding Valley" },
  { value: "Romford", label: "Romford" },
  { value: "Romford_line_off", label: "Romford Line Off" },
  { value: "Rotherhithe", label: "Rotherhithe" },
  { value: "Royal_Albert", label: "Royal Albert" },
  { value: "Royal_Oak_circle", label: "Royal Oak Circle" },
  { value: "Royal_Oak_hnc", label: "Royal Oak Hnc" },
  { value: "Royal_Victoria", label: "Royal Victoria" },
  { value: "Ruislip_Gardens", label: "Ruislip Gardens" },
  { value: "Ruislip_Manor_metropolitan", label: "Ruislip Manor Metropolitan" },
  { value: "Ruislip_Manor_piccadilly", label: "Ruislip Manor Piccadilly" },
  { value: "Ruislip_metropolitan", label: "Ruislip Metropolitan" },
  { value: "Ruislip_piccadilly", label: "Ruislip Piccadilly" },
  { value: "Russell_Square", label: "Russell Square" },
  { value: "STRg", label: "STRg" },
  { value: "Seven_Kings", label: "Seven Kings" },
  { value: "Seven_Sisters", label: "Seven Sisters" },
  { value: "Shadwell", label: "Shadwell" },
  { value: "Shenfield", label: "Shenfield" },
  {
    value: "Shenfield_special_fare_zone",
    label: "Shenfield Special Fare Zone",
  },
  {
    value: "Shepherds_Bush_Market_circle",
    label: "Shepherds Bush Market Circle",
  },
  { value: "Shepherds_Bush_Market_hnc", label: "Shepherds Bush Market Hnc" },
  { value: "Shepherds_Bush_nr", label: "Shepherds Bush" },
  { value: "Shepherds_Bush_tube", label: "Shepherds Bush" },
  { value: "Shoreditch_High_Street", label: "Shoreditch High Street" },
  { value: "Silver_Street", label: "Silver Street" },
  { value: "Sloane_Square_circle", label: "Sloane Square Circle" },
  { value: "Sloane_Square_district", label: "Sloane Square District" },
  { value: "Slough", label: "Slough" },
  { value: "Snaresbrook", label: "Snaresbrook" },
  { value: "South_Acton", label: "South Acton" },
  { value: "South_Ealing", label: "South Ealing" },
  { value: "South_Greenford", label: "South Greenford" },
  { value: "South_Hampstead", label: "South Hampstead" },
  { value: "South_Harrow", label: "South Harrow" },
  { value: "South_Kensington", label: "South Kensington" },
  { value: "South_Kenton_bakerloo", label: "South Kenton Bakerloo" },
  { value: "South_Kenton_overground", label: "South Kenton Overground" },
  { value: "South_Quay", label: "South Quay" },
  { value: "South_Ruislip", label: "South Ruislip" },
  { value: "South_Tottenham", label: "South Tottenham" },
  { value: "South_Wimbledon", label: "South Wimbledon" },
  { value: "South_Wimbledon_zone", label: "South Wimbledon Zone" },
  { value: "South_Woodford", label: "South Woodford" },
  { value: "Southall", label: "Southall" },
  { value: "Southbury", label: "Southbury" },
  { value: "Southend_route", label: "Southend Route" },
  {
    value: "Southern_Brighton_Mainline_route",
    label: "Southern Brighton Mainline Route",
  },
  { value: "Southfields", label: "Southfields" },
  { value: "Southgate", label: "Southgate" },
  { value: "Southwark", label: "Southwark" },
  { value: "St_James_Street", label: "St James Street" },
  { value: "St_Jamess_Park_circle", label: "St Jamess Park Circle" },
  { value: "St_Jamess_Park_district", label: "St Jamess Park District" },
  { value: "St_Johns_Wood", label: "St Johns Wood" },
  { value: "St_Pauls", label: "St Pauls" },
  { value: "Stamford_Brook", label: "Stamford Brook" },
  { value: "Stamford_Hill", label: "Stamford Hill" },
  { value: "Stanmore", label: "Stanmore" },
  { value: "Stansted_Express_route", label: "Stansted Express Route" },
  { value: "Star_Lane", label: "Star Lane" },
  { value: "Stepney_Green_district", label: "Stepney Green District" },
  { value: "Stepney_Green_hnc", label: "Stepney Green Hnc" },
  { value: "Stockwell", label: "Stockwell" },
  { value: "Stoke_Newington", label: "Stoke Newington" },
  { value: "Stonebridge_Park_bakerloo", label: "Stonebridge Park Bakerloo" },
  {
    value: "Stonebridge_Park_overground",
    label: "Stonebridge Park Overground",
  },
  { value: "Stratford", label: "Stratford" },
  { value: "Stratford_High_Street", label: "Stratford High Street" },
  { value: "Stratford_International", label: "Stratford International" },
  { value: "Stratford_validator", label: "Stratford Validator" },
  { value: "Sudbury_Hill", label: "Sudbury Hill" },
  { value: "Sudbury_Town", label: "Sudbury Town" },
  { value: "Suffragette_line_blink", label: "Suffragette Line Blink" },
  { value: "Suffragette_line_off", label: "Suffragette Line Off" },
  { value: "Suffragette_line_route", label: "Suffragette Line Route" },
  {
    value: "Suffragette_line_route_stripe",
    label: "Suffragette Line Route Stripe",
  },
  { value: "Suffragette_line_stations", label: "Suffragette Line Stations" },
  { value: "Surrey_Canal", label: "Surrey Canal" },
  { value: "Surrey_Quays", label: "Surrey Quays" },
  { value: "Surrey_Quays_validator", label: "Surrey Quays Validator" },
  { value: "Swiss_Cottage", label: "Swiss Cottage" },
  { value: "Sydenham", label: "Sydenham" },
  { value: "Taplow", label: "Taplow" },
  { value: "Temple_circle", label: "Temple Circle" },
  { value: "Temple_district", label: "Temple District" },
  { value: "Thames_stripe", label: "Thames Stripe" },
  { value: "Thameslink_blink", label: "Thameslink Blink" },
  { value: "Thameslink_disused_blink", label: "Thameslink Disused Blink" },
  { value: "Thameslink_off", label: "Thameslink Off" },
  { value: "Thameslink_route", label: "Thameslink Route" },
  { value: "Theobalds_Grove", label: "Theobalds Grove" },
  { value: "Theydon_Bois", label: "Theydon Bois" },
  { value: "Tooting_Bec", label: "Tooting Bec" },
  { value: "Tooting_Broadway", label: "Tooting Broadway" },
  { value: "Tottenham_Court_Road_cr", label: "Tottenham Court Road" },
  { value: "Tottenham_Hale", label: "Tottenham Hale" },
  { value: "Totteridge_And_Whetstone", label: "Totteridge And Whetstone" },
  { value: "Tower_Gateway", label: "Tower Gateway" },
  { value: "Tower_Hill", label: "Tower Hill" },
  { value: "Tramlink_blink", label: "Tramlink Blink" },
  { value: "Tramlink_off", label: "Tramlink Off" },
  { value: "Tramlink_route", label: "Tramlink Route" },
  { value: "Tramlink_stations", label: "Tramlink Stations" },
  { value: "Tufnell_Park", label: "Tufnell Park" },
  { value: "Turkey_Street", label: "Turkey Street" },
  { value: "Turnham_Green_district", label: "Turnham Green District" },
  { value: "Turnham_Green_piccadilly", label: "Turnham Green Piccadilly" },
  { value: "Turnham_Green_zone", label: "Turnham Green Zone" },
  { value: "Turnpike_Lane", label: "Turnpike Lane" },
  { value: "Twyford", label: "Twyford" },
  { value: "Upminster", label: "Upminster" },
  { value: "Upminster_Bridge", label: "Upminster Bridge" },
  { value: "Upney", label: "Upney" },
  { value: "Upper_Holloway", label: "Upper Holloway" },
  { value: "Upton_Park_district", label: "Upton Park District" },
  { value: "Upton_Park_hnc", label: "Upton Park Hnc" },
  { value: "Uxbridge_metropolitan", label: "Uxbridge Metropolitan" },
  { value: "Uxbridge_piccadilly", label: "Uxbridge Piccadilly" },
  { value: "Vauxhall", label: "Vauxhall" },
  { value: "Vauxhall_zone", label: "Vauxhall Zone" },
  { value: "Victoria", label: "Victoria" },
  { value: "Victoria_Coach_Station", label: "Victoria Coach Station" },
  { value: "Victoria_Coach_path", label: "Victoria Coach Path" },
  { value: "Victoria_line_blink", label: "Victoria Line Blink" },
  { value: "Victoria_line_off", label: "Victoria Line Off" },
  { value: "Victoria_line_route", label: "Victoria Line Route" },
  { value: "Victoria_line_stations", label: "Victoria Line Stations" },
  { value: "Walthamstow_Central", label: "Walthamstow Central" },
  { value: "Walthamstow_Queens_Road", label: "Walthamstow Queens Road" },
  { value: "Wandsworth_Road", label: "Wandsworth Road" },
  { value: "Wanstead", label: "Wanstead" },
  { value: "Wanstead_Park", label: "Wanstead Park" },
  { value: "Wapping", label: "Wapping" },
  { value: "Warren_Street", label: "Warren Street" },
  { value: "Warwick_Avenue", label: "Warwick Avenue" },
  { value: "Waterloo", label: "Waterloo" },
  {
    value: "Waterloo_and_City_line_blink",
    label: "Waterloo And City Line Blink",
  },
  { value: "Waterloo_and_City_line_off", label: "Waterloo And City Line Off" },
  {
    value: "Waterloo_and_City_line_route",
    label: "Waterloo And City Line Route",
  },
  { value: "Watford", label: "Watford" },
  { value: "Watford_High_Street", label: "Watford High Street" },
  { value: "Watford_Junction", label: "Watford Junction" },
  {
    value: "Watford_Junction_special_fare_zone",
    label: "Watford Junction Special Fare Zone",
  },
  { value: "Weaver_line_blink", label: "Weaver Line Blink" },
  { value: "Weaver_line_off", label: "Weaver Line Off" },
  { value: "Weaver_line_routes", label: "Weaver Line Routes" },
  { value: "Weaver_line_routes_stripe", label: "Weaver Line Routes Stripe" },
  { value: "Weaver_line_stations", label: "Weaver Line Stations" },
  { value: "Wembley_Central", label: "Wembley Central" },
  { value: "Wembley_Park", label: "Wembley Park" },
  { value: "West_Acton", label: "West Acton" },
  { value: "West_Brompton", label: "West Brompton" },
  { value: "West_Brompton_validator", label: "West Brompton Validator" },
  { value: "West_Croydon", label: "West Croydon" },
  { value: "West_Drayton", label: "West Drayton" },
  { value: "West_Ealing", label: "West Ealing" },
  { value: "West_Finchley", label: "West Finchley" },
  { value: "West_Ham", label: "West Ham" },
  { value: "West_Hampstead", label: "West Hampstead" },
  { value: "West_Harrow", label: "West Harrow" },
  { value: "West_India_Quay", label: "West India Quay" },
  { value: "West_Kensington", label: "West Kensington" },
  { value: "West_London_line_route", label: "West London Line Route" },
  { value: "West_Ruislip", label: "West Ruislip" },
  { value: "West_Ruislip_Ickenham_osi", label: "West Ruislip Ickenham Osi" },
  { value: "West_Silvertown", label: "West Silvertown" },
  { value: "Westbourne_Park_circle", label: "Westbourne Park Circle" },
  { value: "Westbourne_Park_hnc", label: "Westbourne Park Hnc" },
  { value: "Westferry", label: "Westferry" },
  { value: "Westminster", label: "Westminster" },
  { value: "White_City", label: "White City" },
  { value: "White_City_Wood_Lane_osi", label: "White City Wood Lane Osi" },
  { value: "White_Hart_Lane", label: "White Hart Lane" },
  { value: "Whitechapel", label: "Whitechapel" },
  { value: "Whitechapel_validator", label: "Whitechapel Validator" },
  { value: "Willesden_Green", label: "Willesden Green" },
  { value: "Willesden_Green_zone", label: "Willesden Green Zone" },
  { value: "Willesden_Junction", label: "Willesden Junction" },
  {
    value: "Willesden_Junction_validator",
    label: "Willesden Junction Validator",
  },
  { value: "Willesden_Junction_zone", label: "Willesden Junction Zone" },
  { value: "Wimbledon", label: "Wimbledon" },
  { value: "Wimbledon_Park", label: "Wimbledon Park" },
  { value: "Wimbledon_validator", label: "Wimbledon Validator" },
  {
    value: "Windrush_line_Battersea_Park_branch",
    label: "Windrush Line Battersea Park Branch",
  },
  {
    value: "Windrush_line_Battersea_Park_branch_blink",
    label: "Windrush Line Battersea Park Branch Blink",
  },
  {
    value: "Windrush_line_Battersea_Park_branch_stripe",
    label: "Windrush Line Battersea Park Branch Stripe",
  },
  { value: "Windrush_line_blink", label: "Windrush Line Blink" },
  { value: "Windrush_line_route", label: "Windrush Line Route" },
  { value: "Windrush_line_route_stripe", label: "Windrush Line Route Stripe" },
  { value: "Windrush_line_stations", label: "Windrush Line Stations" },
  { value: "Wood_Green", label: "Wood Green" },
  { value: "Wood_Lane", label: "Wood Lane" },
  { value: "Wood_Street", label: "Wood Street" },
  { value: "Woodford", label: "Woodford" },
  { value: "Woodgrange_Park", label: "Woodgrange Park" },
  { value: "Woodside_Park", label: "Woodside Park" },
  { value: "Woolwich", label: "Woolwich" },
  { value: "Woolwich_Arsenal", label: "Woolwich Arsenal" },
];
